<?php

namespace ModelBundle\Repository\Enum;

/**
 * FormaKursuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormaKursuRepository extends \Doctrine\ORM\EntityRepository
{
}
