<?php

namespace ModelBundle\Repository\Enum;

/**
 * TypRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypRepository extends \Doctrine\ORM\EntityRepository
{
}
