imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ModelBundle/Resources/config/services.yml" }
    - { resource: "@ProgramBundle/Resources/config/services.yml" }
    - { resource: "@EfektKsztalceniaBundle/Resources/config/services.yml" }
    - { resource: "@PrzedmiotBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pl

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    templating:
        engines: ['twig']
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

knpu_oauth2_client:
    clients:
        # the key "facebook_main" can be anything, it
        # will create a service: "knpu.oauth2.client.facebook_main"
        facebook_main:
            # this will be one of the supported types
            type: facebook
            client_id: 479817735781470
            client_secret: 3030529d41a3d707d3ad8ab667d9eeab
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_facebook_check
            # route parameters to pass to your route, if needed
            redirect_params: {}
            graph_api_version: v2.12

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# KNP Paginator
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query parameter name
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

# app/config/config.yml
easy_admin:
    site_name: PSI
    design:
        menu:
            - label: Enums
              children:
                  - FormaZajec
                  - Jezyk
                  - ObszarKsztalcenia
                  - PoziomKsztalcenia
                  - ProfilKsztalcenia
                  - Rodzaj
                  - SposobZaliczenia
                  - TypStudiow
                  - Tytul
                  - Wydzial
                  - Zakres
                  - FormaKursu
                  - Typ
            - label: Program
              children:
                  - KierunekStudiow
                  - Semestr
                  - ProgramStudiow
                  - ProgramKsztalcenia
                  - PlanStudiow
            - label: Efekty kształcenia
              children:
                  - EfektKierunkowy
                  - EfektMinisterialny
                  - EfektPrzedmiotowy
            - label: Przedmiot
              children:
                  - GrupaKursow
                  - KartaPrzedmiotu
                  - Kurs
                  - ModulKsztalcenia
                  - Przedmiot
            - label: Użytkownicy
              children:
                  - User

    entities:
        FormaZajec:
            class: ModelBundle\Entity\Enum\FormaZajec
            label: Forma zajęć
        FormaKursu:
            class: ModelBundle\Entity\Enum\FormaKursu
            label: Forma kursu
        Typ:
            class: ModelBundle\Entity\Enum\Typ
            label: Typ
        Jezyk:
            class: ModelBundle\Entity\Enum\Jezyk
            label: Język
        ObszarKsztalcenia:
            class: ModelBundle\Entity\Enum\ObszarKsztalcenia
            label: Obszar kształcenia
        PoziomKsztalcenia:
            class: ModelBundle\Entity\Enum\PoziomKsztalcenia
            label: Poziom kształcenia
        ProfilKsztalcenia:
            class: ModelBundle\Entity\Enum\ProfilKsztalcenia
            label: Profil kształcenia
        Rodzaj:
            class: ModelBundle\Entity\Enum\Rodzaj
            label: Rodzaj
        SposobZaliczenia:
            class: ModelBundle\Entity\Enum\SposobZaliczenia
            label: Sposób zaliczenia
        TypStudiow:
            class: ModelBundle\Entity\Enum\TypStudiow
            label: Typ studiów
        Tytul:
            class: ModelBundle\Entity\Enum\Tytul
            label: Tytuł
        Wydzial:
            class: ModelBundle\Entity\Enum\Wydzial
            label: Wydział
        Zakres:
            class: ModelBundle\Entity\Enum\Zakres
            label: Zakres
        KierunekStudiow:
            class: ModelBundle\Entity\KierunekStudiow
            label: Kierunek studiów
        PlanStudiow:
            class: ModelBundle\Entity\PlanStudiow
            label: Plan studiów
        ProgramKsztalcenia:
            class: ModelBundle\Entity\ProgramKsztalcenia
            label: Program kształcenia
        ProgramStudiow:
            class: ModelBundle\Entity\ProgramStudiow
            label: Program studiów
        Semestr:
            class: ModelBundle\Entity\Semestr
            label: Semestr
        EfektPrzedmiotowy:
            class: ModelBundle\Entity\EfektPrzedmiotowy
            label: Efekt przedmiotowy
        EfektMinisterialny:
            class: ModelBundle\Entity\EfektMinisterialny
            label: Efekt ministerialny
        EfektKierunkowy:
            class: ModelBundle\Entity\EfektKierunkowy
            label: Efekt kierunkowy
        GrupaKursow:
            class: ModelBundle\Entity\GrupaKursow
            label: Grupa kursów
        KartaPrzedmiotu:
            class: ModelBundle\Entity\KartaPrzedmiotu
            label: Karta przedmiotu
        Kurs:
            class: ModelBundle\Entity\Kurs
            label: Kurs
        Przedmiot:
            class: ModelBundle\Entity\Przedmiot
            label: Przedmiot
        ModulKsztalcenia:
            class: ModelBundle\Entity\ModulKsztalcenia
            label: Moduł kształcenia
        User:
            class: UserBundle\Entity\User
            label: Użytkownicy
