services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    my_facebook_authenticator:
        class: UserBundle\Security\MyFacebookAuthenticator
#        autowire: true
        # use autowiring, OR you can specify the argument manually
        arguments:
             - '@oauth2.registry'
             - '@doctrine.orm.entity_manager'
             - '@router'