services:
    model.service.paginator_helper:
        class: ModelBundle\Service\PaginatorHelper
        calls:
            - [setPaginator, ['@knp_paginator']]
            - [setEm, ['@Doctrine\ORM\EntityManagerInterface']]
