<?php

namespace ModelBundle\Repository;

/**
 * CelePrzedmiotuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CelePrzedmiotuRepository extends \Doctrine\ORM\EntityRepository
{
}
