<?php

namespace ModelBundle\Repository;

/**
 * EfektPrzedmiotowyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EfektPrzedmiotowyRepository extends \Doctrine\ORM\EntityRepository
{
}
