<?php

namespace ModelBundle\Repository;

/**
 * EfektKierunkowyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EfektKierunkowyRepository extends \Doctrine\ORM\EntityRepository
{
}
