<?php

namespace ModelBundle\Repository;

/**
 * EfektKsztalceniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EfektKsztalceniaRepository extends \Doctrine\ORM\EntityRepository
{
}
