<?php

namespace ModelBundle\Repository;

/**
 * EfektMinisterialnyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EfektMinisterialnyRepository extends \Doctrine\ORM\EntityRepository
{
}
