<?php

namespace ModelBundle\Repository;

/**
 * FormaZajecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormaZajecRepository extends \Doctrine\ORM\EntityRepository
{
}
