<?php

namespace ModelBundle\Repository;

/**
 * GrupaKursowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupaKursowRepository extends \Doctrine\ORM\EntityRepository
{
}
