<?php

namespace ModelBundle\Repository;

/**
 * JezykRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JezykRepository extends \Doctrine\ORM\EntityRepository
{
}
