<?php

namespace ModelBundle\Repository;

/**
 * KartaPrzedmiotuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KartaPrzedmiotuRepository extends \Doctrine\ORM\EntityRepository
{
}
