<?php

namespace ModelBundle\Repository;

/**
 * KierunekStudiowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KierunekStudiowRepository extends \Doctrine\ORM\EntityRepository
{
}
