<?php

namespace ModelBundle\Repository;

/**
 * LiteraturaPodstawowaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiteraturaPodstawowaRepository extends \Doctrine\ORM\EntityRepository
{
}
