<?php

namespace ModelBundle\Repository;

/**
 * LiteraturaUzupelniajacaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiteraturaUzupelniajacaRepository extends \Doctrine\ORM\EntityRepository
{
}
