<?php

namespace ModelBundle\Repository;

/**
 * ModulKsztalceniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModulKsztalceniaRepository extends \Doctrine\ORM\EntityRepository
{
}
