<?php

namespace ModelBundle\Repository;

/**
 * NarzedziaDydaktyczneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NarzedziaDydaktyczneRepository extends \Doctrine\ORM\EntityRepository
{
}
