<?php

namespace ModelBundle\Repository;

/**
 * ObszarKsztalceniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObszarKsztalceniaRepository extends \Doctrine\ORM\EntityRepository
{
}
