<?php

namespace ModelBundle\Repository;

/**
 * OcenaOsiagnieciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OcenaOsiagnieciaRepository extends \Doctrine\ORM\EntityRepository
{
}
