<?php

namespace ModelBundle\Repository;

/**
 * PlanStudiowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanStudiowRepository extends \Doctrine\ORM\EntityRepository
{
}
