<?php

namespace ModelBundle\Repository;

/**
 * PoziomKsztalceniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoziomKsztalceniaRepository extends \Doctrine\ORM\EntityRepository
{
}
