<?php

namespace ModelBundle\Repository;

/**
 * ProfilKsztalceniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilKsztalceniaRepository extends \Doctrine\ORM\EntityRepository
{
}
