<?php

namespace ModelBundle\Repository;

/**
 * ProgramStudiowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramStudiowRepository extends \Doctrine\ORM\EntityRepository
{
}
