<?php

namespace ModelBundle\Repository;

/**
 * ProgramKsztalceniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramKsztalceniaRepository extends \Doctrine\ORM\EntityRepository
{
}
