<?php

namespace ModelBundle\Repository;

/**
 * PrzedmiotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrzedmiotRepository extends \Doctrine\ORM\EntityRepository
{
}
