<?php

namespace ModelBundle\Repository;

/**
 * RodzajRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RodzajRepository extends \Doctrine\ORM\EntityRepository
{
}
