<?php

namespace ModelBundle\Repository;

/**
 * SemestrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemestrRepository extends \Doctrine\ORM\EntityRepository
{
}
