<?php

namespace ModelBundle\Repository;

/**
 * SposobZaliczeniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SposobZaliczeniaRepository extends \Doctrine\ORM\EntityRepository
{
}
