<?php

namespace ModelBundle\Repository;

/**
 * TresciProgramoweRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TresciProgramoweRepository extends \Doctrine\ORM\EntityRepository
{
}
