<?php

namespace ModelBundle\Repository;

/**
 * TypStudiowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypStudiowRepository extends \Doctrine\ORM\EntityRepository
{
}
