<?php

namespace ModelBundle\Repository;

/**
 * TytulRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TytulRepository extends \Doctrine\ORM\EntityRepository
{
}
