<?php

namespace ModelBundle\Repository;

/**
 * WydzialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WydzialRepository extends \Doctrine\ORM\EntityRepository
{
}
