<?php

namespace ModelBundle\Repository;

/**
 * WymaganiaWstepneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WymaganiaWstepneRepository extends \Doctrine\ORM\EntityRepository
{
}
