<?php

namespace ModelBundle\Repository;

/**
 * ZakresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZakresRepository extends \Doctrine\ORM\EntityRepository
{
}
